[package]
name = "vcfviewer"
version = "0.1.0"
authors = ["Francesco Tabaro <francesco.tabaro@gmail.com>"]

[dependencies]
rouille = "2.0.0"
flate2 = "1.0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
docopt = "0.8.3"
chrono = "0.4"